# This is our custom message for pulses

std_msgs/String detector_id
std_msgs/Float64 frequency
builtin_interfaces/Time pulse_start_time
builtin_interfaces/Time pulse_end_time
builtin_interfaces/Time predicted_next
std_msgs/Float64 snr
std_msgs/Float64 snr_per_sample
std_msgs/Float64 psd_sn
std_msgs/Float64 psd_n
std_msgs/Float64 dft_real
std_msgs/Float64 dft_imag
std_msgs/UInt16 group_ind
std_msgs/Float64 group_snr
std_msgs/Bool detection_status
std_msgs/Bool confirmed_status

 